export const homeObjOne = {
    id: 'about',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'About Myself',
    headline: 'I am a Graduate with a B.S. in Software Engineering and a minor in Computer Science from the Pennsylvania State University.',
    buttonLabel: 'Skills',
    description: `As a software engineer, I enjoy turning an idea into a reality through the use of good code and design. My goal is to build scalable and efficient applications that work in the background, while combining it with a user friendly interface and engaging experience. When I'm not coding, I enjoy being outside whether that's hiking, exploring or snowboarding. I also have a deep passion for cooking and trying new things`,
    imgStart: true,
    img: require('../../assets/images/img-1.svg').default,
    alt: 'Moonlight (Undraw.co)',
    dark: true,
    primary: true,
    darkText: false,
}

export const homeObjTwo = {
    id: 'skills',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Technical Skills',
    headline: '',
    buttonLabel: 'Projects',
    description: ``,
    imgStart: false,
    img: require('../../assets/images/img-2.svg').default,
    alt: 'Resume (Undraw.co)',
    dark: false,
    primary: false,
    darkText: true,
}

export const homeObjThree = {
    id: 'projects',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Projects',
    buttonLabel: 'Contact',
    description: ``,
    imgStart: true,
    img: require('../../assets/images/img-3.svg').default,
    alt: 'Coding (Undraw.co)',
    dark: true,
    primary: true,
    darkText: false,
}